version: '3.8'

services:

  bedatabase: 
    container_name: bemariadb
    image: mariadb:10.5
    ports: "3306:3306"

  bepython:
    container_name: bepython
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"