# Generated by Django 4.0.4 on 2022-04-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
