# Generated by Django 4.0.4 on 2022-04-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_game_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.CharField(max_length=200)),
                ('customerId', models.CharField(max_length=200)),
                ('subCategory', models.DateTimeField()),
                ('price', models.FloatField(blank=True)),
            ],
        ),
    ]
