# Generated by Django 4.0.4 on 2022-04-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='subCategory',
            new_name='timestamp',
        ),
    ]
